server:
  port: 8082


spring:
  application:
    name: survey-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/survey_db?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
eureka:
  instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10
      prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
