server:
  port: 8085 

spring:
  application:
    name: reportes-service 
  config:
    import: optional:configserver:http://localhost:8888
  autoconfigure:
     exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/